### ISSUE TITLE
Enable keyboard-based search in collaboration diagram

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#113]
Maybe even a small text field at the top that filters members containing the search string.

**Comment by andykenner** [comment]
the searchbox has a bad behavior, please make sure to have the first key in the textfield also. if hello is typed the "h" is use to open the dialog and is missing, so the textbox shows ello

**Comment by andykenner** [comment]
Another improvement may be a trim, if something like "hello " is typed in.

**Comment by fbenduhn** [comment]
The search box could be embedded into bar on top of the collaboration view instead of openening a separate dialog.

**Comment by fbenduhn** [comment]
merged with #181
