### ISSUE TITLE
[project settings] the model file 'model.xml' is created in project root

### ISSUE THREAD

**Issue by anb0s** [tthuem/FeatureIDE#123]
The model file (model.xml) is always created in project root and cannot be renamed or moved to other (sub) directory. During model creation i've entered a sub path to store the model file (e.g. "cmm\model.xml"). The file "cmm\model.xml" was created, but also a second file in project root was created.

**Comment by RSchroeter** [comment]
In the current version of FeatureIDE it is possible to create some new model files in a (sub) directory. Afterwards, it is possible to reference these model artifacts out of the main model (project root). This functionality is only available, if the project is a mutli software product line (MPL) project. Therefore, it is possible to convert an ordinary FeatureIDE project to an MPL project (FeatureIDE -> Convert to Multi Software Product Line).

**Comment by anb0s** [comment]
Thank You! I will try the new version with MPL project. I've installed version FeatureIDE 2.7.2 and cannot find "Convert to Multi Software Product Line". Do you know the release date of version 2.7.3?

**Comment by tthuem** [comment]
The new version will probably be published next week. You may tryout the nightly builds in the mean time: http://wwwiti.cs.uni-magdeburg.de/iti_db/research/featureide/nightly/p2-updateSite/

**Comment by anb0s** [comment]
I've just tried the nightly build and can work with example received from RSchroeter. I will investigate the MPL solution and report some feedback. Thank You!

Small if i open MPL project then some exceptions are thrown, but the project works. Should i create new issue?
e.g.:
...
An internal error occurred during: "Load Model".
java.lang.NullPointerException
	at de.ovgu.featureide.core.internal.FeatureProject$4.run(FeatureProject.java:911)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
...

**Comment by tthuem** [comment]
Yes, please create a new issue and include some information how to reproduce it. Many thanks in advance.
