### ISSUE TITLE
Antenna: Use the preprocessor for other sw artifacts than java code

### ISSUE THREAD

**Issue by joliebig** [tthuem/FeatureIDE#157]
Short question: Is it possible to use the antenna preprocessor for something else than java code. I'd like to annotate html. Is it possible with FeatureIDE? Is it planned? Any best practices or workarounds?

**Comment by tthuem** [comment]
As the questions seems to be answered, I'm closing the issue. Nevertheless, let us know which specific languages are needed and do cause problems (even with Munge).
