### ISSUE TITLE
Test FeatureIDE for Eclipse 4.4

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#160]
Check whether all functionalities of FeatureIDE work with Eclipse 4.4.

**Comment by tthuem** [comment]
Is anyone already using Eclipse 4.4 for FeatureIDE and can report potential problems?

**Comment by tthuem** [comment]
From the FeatureIDE meeting: there are no known bugs and we will prepare the new version of FeatureIDE based on Eclipse 4.4.

TODO: Update the compatibility on our website.

**Comment by tthuem** [comment]
Unfortunately, AspectJ Development Tools are not yet released for Eclipse 4: http://eclipse.org/ajdt/downloads/

Shall we create our new pre-packaged version of Eclipse based on Eclipse 4.3 or with a development version of AJDT then?!?

**Comment by fbenduhn** [comment]
I think a development version of AJDT is fine as users will still be able to update the AJDT version of the prepackaged FeatureIDE if they need.

**Comment by tthuem** [comment]
Sounds reasonable, I'll create the next pre-packaged version based on Eclipse 4.4 and development build of AspectJ.
