### ISSUE TITLE
FeatureIDE not responsive when adding a globalActionHandler for Printing

### ISSUE THREAD

**Issue by ckruczek** [tthuem/FeatureIDE#164]
Following Configuration:

**Operating System:**
 Linux archlinux 3.17.2-1-ARCH

**Java Version:**
openjdk version "1.8.0_25"
OpenJDK Runtime Environment (build 1.8.0_25-b18)
OpenJDK 64-Bit Server VM (build 25.25-b02, mixed mode)

**Eclipse Version:**
Tested on Eclipse 4.2 as well as on 4.4.1

With this configuration, and the following line of code commented in:

**CollaborationView.java Method *contributeToActionBars***

```java
private void contributeToActionBars() {
		IActionBars bars = getViewSite().getActionBars();

		//bars.setGlobalActionHandler(ActionFactory.PRINT.getId(), printAction);

		fillLocalToolBar(bars.getToolBarManager());
	}
```

everythin works fine. But as soon as I comment this line out the whole Eclipse FeatureIDE instance is not responsive, after I do any interaction with the CollaborationDiagram, anymore.

Could somebody validate this with Windows or any other Linux-Distribution(despite Ubuntu would be the best).

**Comment by tthuem** [comment]
Try to find out the cause more specifically. Does it happen for all example projects on Linux? Is it specific to a certain composer? Does it happen also for other FeatureIDE views and what are potential differences?

**Comment by ckruczek** [comment]
Could not be reproduced anymore with the current version from master. So I declare this issue as fixed.
