### ISSUE TITLE
FeatureIDE 2.6.1 for Linux does not work

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#165]
The prepacked Feature IDE Version for Linux 64 bit (http://wwwiti.cs.uni-magdeburg.de/iti_db/research/featureide/downloads/eclipse3.6-featureide2.6.1-linux_x86_64.tar.bz2) does not work properly:

After starting Eclipse, the package explorer cannot be initialized and no project can be imported.

**Comment by tthuem** [comment]
We need to create a new version anyway (see #166 ) and should check whether the bug still occurs.
