### ISSUE TITLE
Lazy Loading of Configuration Tree

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#167]
For large model files the loading process for the configuration tree is to slow. 
In order to increase the speed from the users perspective the trees content should be loaded "lazy", which means a priority based tree building depending on the current portion of view inside the tree control. This should include: 
* Run entire loading independently from the ui thread to stop "hang" eclipse while loading
* Mark nodes (auto/manuell selected/deselected) with priority to the current field of view inside the control. Pending nodes (e.g. labeled als "state unknown" or "pending") should be visualized with a loading circle and/or disabling the nodes checkbox.

**Comment by skrieter** [comment]
Fixed and merged into Master.
