### ISSUE TITLE
Missing ifdefs in collaboration diagram

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#168]
In the following project, some ifdefs are not shown in the collaboration diagram:

https://github.com/DB-SE/isp2014.anton.anders/tree/master/Aufgabe3

For example, in App.java the following statements are ignored:

//#ifndef INPUT_CONSOLE 
//#ifdef INPUT_CONSOLE
//#ifdef OUTPUT_CONSOLE
//#ifdef TXT

**Comment by pinnecke** [comment]
> In the following project, some ifdefs are not shown in the collaboration diagram

Cannot reproduce this with current master checkout, or do I miss something?

![1](https://cloud.githubusercontent.com/assets/3775170/6583020/8aa5bde4-c761-11e4-94e8-3cede6fc8970.png)

and

![2](https://cloud.githubusercontent.com/assets/3775170/6583021/8ac40af6-c761-11e4-89a8-9028113ba95c.png)

**Comment by pinnecke** [comment]
Extracted

>An internal error occurred during: "Calculate de.ovgu.featureide.ui.statistics.core.composite.lazyimplementations.DirectivesNode".
Index: 0, Size: 0

to #225 and I will work on that.

**Comment by pinnecke** [comment]
Please check by yourself if the problem with the collaboration diagram exists on your machine with current master. If not, please close this issue. Otherwise please describe more in detail when the problem occurs.

**Comment by tthuem** [comment]
Seems to work now:

![works](https://cloud.githubusercontent.com/assets/5330357/6596548/a758c898-c7f5-11e4-915b-37316ed5dd3e.png)
