### ISSUE TITLE
Only show menu entries for projects for which their functionality is actually available

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#173]
or at least set them gray

Project Menu: 
FeatureIDE >
- feature-based...
- metaproduct
- fuji

see: change composer entires

**Comment by tthuem** [comment]
See #24, could be combined

**Comment by meinicke** [comment]
Also move Menu\"FeatureIDE"\"Add FeatureIDE Nature" to Menu\"configure"\"Add FeatureIDE Nature" as other plugins do it this way (e.g., Scala, Maven)

It is just annoying if this entry is at any project

**Comment by tthuem** [comment]
Menu looks fine. I'm just wondering whether Documentation is really available for all composers and even for feature modeling (only). When I tried it there was no exception, but also nothing happened.
