### ISSUE TITLE
ConstraintDialog closing options

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#177]
- This leads to closing the dialog by accident when trying to close "proposal" popup. If there is no other way remove the ESC hotkey. 
- By context the default button for this dialog changes between "cancel" and "ok". Check this if this leads to confusing moments.
- Closing the dialog for non-syntax errors should work in any case. But show a warning message with reminder checkbox

**Comment by tthuem** [comment]
"Closing the dialog for non-syntax errors should work in any case. But show a warning message with reminder checkbox" is rather uncommon in Eclipse. I would rather just show a warning a the top of the dialog and allow closing without any further messages.

**Comment by pinnecke** [comment]
Additioanlly: Start ConstraintDialog input with selected feature

**Comment by pinnecke** [comment]
**This leads to closing the dialog by accident when trying to close "proposal" popup. If there is no other way remove the ESC hotkey**

This is solved. If the the proposal pop up is open and the user hits ESC the pop up will be closed not the dialog. If there is no proposal pop up open, the dialog is closed.


**By context the default button for this dialog changes between "cancel" and "ok". Check this if this leads to confusing moments.**

To my mind the logic is well and intuitive.

**Closing the dialog for non-syntax errors should work in any case. But show a warning message with reminder checkbox**

I removed the disabling of "OK" button if a (non-wellformed) check fails which means the button is furthermore labeled as "Save anyway" and accessible. If the all checks passes successfully the button turns to "Create/Update Constraint" mode. The OK button is now only disabled If the input is not well formed or empty.

**Comment by pinnecke** [comment]
**  Start ConstraintDialog input with selected feature **
Added. Moreover if a user selects a feature F, the corresponding popup menu is called "Create Constraint starting with F".

**Comment by pinnecke** [comment]
Please review.

**Comment by pinnecke** [comment]
Solved and committed into master.
