### ISSUE TITLE
Start ConstraintDialog input with selected feature

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#179]
If a feature is selected inside the model and by clicking "Create Constraint" in pop up the ConstraintEditor should automatically insert the selected feature as starting point for the constraint. Example: Feature "A" is selected in the model, click on "Create Constraint" then the edit control in ConstraintEditor should already have "A" as Text when opening the Editor.

**Comment by tthuem** [comment]
Too fine-grained issue. Simply do it, if you think it is useful (as part of another issue with the dialog).
