### ISSUE TITLE
Collaboration model not found for newly created FeatureHouse projects

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#184]
* Opening any file from the following projects (FeatureHouse project names end with number 5) results in a collaboration diagram showing only the features: https://github.com/DB-SE
* At the same time, the collaboration diagram works as expected for FeatureHouse examples.
* Swichting to older versions of FeatureIDE does not help !!! Which indicates that there is something wrong with the creation of FeatureHouse projects.
* Playing around with the Fuji option, the refresh button, and rebuild did not help.

Part of that behavior could even be reproduced on Marcus' machine.

**Comment by meinicke** [comment]
The bug was caused because the folder name of the project did not mach the project's name
