### ISSUE TITLE
Wrong calculation of redundant constraints in constraint dialog

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#190]
Changing the selected constraint to the one displayed in the editor does not cause a redundant constraint:

![bug2](https://cloud.githubusercontent.com/assets/5330357/6003441/2329c18c-aafc-11e4-8638-d983a5e93832.png)

Also the message is missleading: "The constraint is redundant." would be better.

**Comment by tthuem** [comment]
In addition, the feature model editor misses that the constraint 'A implies B' is redundant (before changing the second constraint). Note that all calculations are turned on.

**Comment by pinnecke** [comment]
Cannot reproduce the bug. I created the model above, selected "A or C implies B", edit this constraint to "C implies B" and everything works. 
![bildschirmfoto 2015-02-05 um 15 47 43](https://cloud.githubusercontent.com/assets/3775170/6062231/5da283f4-ad4e-11e4-9ec5-38452b9d4b98.png)

**Comment by pinnecke** [comment]
I changed the description for redundancy to "The constraint is redundant.". This change is available in remote branch **issue_190**. Please do not merge until we are happy with the core problem ;)

**Comment by tthuem** [comment]
Unfortunately, I could not reproduce it either. So if it appears again, we should reopen the issue. Please close the issue once you merged the branch.
