### ISSUE TITLE
Feature interaction between automated analyses in feature diagram and edits view

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#202]
When turning the automated analyses of feature diagram off, the edits view is not updated either. Even though the button on top of the edits view says it is turned on and the context menu in feature diagram does not mention edits. This is rather unintuitive and I would recommend that the context menu of the feature diagram does not affect the edits view.

**Comment by meinicke** [comment]
I cannot reproduce the defect. (i.e. edits view works when calculations are off)
Please give a more detailed description when the defect happens.

Maybe you have disabled the automated analyses of the edits view (the left butten must not be pressed)

**Comment by tthuem** [comment]
Right, seems to work now with the most current version.
