### ISSUE TITLE
Selecting several features in manual layout is not possible anymore

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#203]
Choosed an hello world project, switched to manual layout and tried to select several features. The selection disappears after less then a second.

**Comment by skrieter** [comment]
Could not reproduce this issue.
(used Eclipse Version 4.3 SR2)
Can you provide more details?

**Comment by fbenduhn** [comment]
Happens if you use ctrl + left mouse button to select multiple features.

**Comment by tthuem** [comment]
Could still reproduce it with the current master and Eclipse 4.4.1.
