### ISSUE TITLE
ConstraintDialog does not allow feature names with whitespaces anymore

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#210]
**Extract this issue from** #189 because it is not related to the topic in #189.

> Even worse, creating a constraint simply by clicking does not work anymore, too:

![syntax-bug](https://cloud.githubusercontent.com/assets/5330357/6037400/97a9856c-ac53-11e4-8e55-850c18b20b2a.png)

> Clicking on a feature with white spaces needs to add " around the name to avoid syntax errors. I'm pretty sure that white spaces in feature names were supported in prior versions. Also, we've had better error explanations than "there is a syntax error". :(

**Comment by pinnecke** [comment]
According to the *isWellformed* method,

```
private boolean isWellformed(FeatureModel featureModel, String con) {
		NodeReader nodereader = new NodeReader();
		boolean isWellformed = nodereader.isWellFormed(con, featureModel.getFeatureNames());

		return isWellformed;
	}
```

 the input ```B or B [2]```is indeed **not valid**, and therefore the syntax highlighter marks the entire line as syntactically wrong. However, ```B or "B [2]"`` is right and could be saved although it is the marking is not correct (which is a bit cosmetic).

**Comment by pinnecke** [comment]
Observation: According to current syntax check, ``B or " B [2]   "  ``is also not right, so I assume a **whitespace containing feature name** have to be set in quotes and each other feature name is also valid in quotes as long, as this quotes doesn't add new whitespace at the beginning or ending. This means ``"A"`` is correct for ``A`` where as ``"     A  "`` is not correct.

Solution: The syntax highlighter depends on known (possible) words. By adding a feature name twice, one with the standard name and one with the feature's name in quotes, solves this issue.

**Comment by tthuem** [comment]
Why adding twice? Shouldn't it work to add features without whitespaces as usual and those with whitespaces with quotes only? The view listing all features could also show exactly those features with quotes and others not. Inserting into the text field should then be trivial.

**Comment by pinnecke** [comment]
Of course ``"My Feature With Space"`` have to be in quotes.That's, but for non-whitespace characters it is *optional* to add quotes. isn't it? When leaving this out, ``"A"`` will be interpreted as invalid feature name although it is possible (because ``boolean isWellformed(FeatureModel, String)``will accept it.

**Comment by tthuem** [comment]
I don't think it is useful to have two representations of A namely A and "A". It may confuse users to see this feature duplicate in content assist. However, if this simplifies the solution, go ahead. I can live with it.

**Comment by pinnecke** [comment]
I also figured out two little bugs:
1. When clicking on the feature list twice to add this into the input text field and the feature name contains a whitespace, currently the automatically surrounding with quotes is missing (**solved**)
2. When starting the dialog with a given constraint (which is possible since clicking on a feature *A* in feature diagram shows a option *Create Constraint starting with "A"*), quotes for white-space feature names are also missing (**solved**)

**Comment by pinnecke** [comment]
> I don't think it is useful to have two representations of A namely A and "A". It may confuse users to see this feature duplicate in content assist. However, if this simplifies the solution, go ahead. I can live with it.

It does not simplifies the solution but it is consistent to the result of the *isWellformed* method and previous behavior. That's because you will not get an error for those optional quotes and so the syntax highlighter should not confuse you with wrong information ;)

**Comment by pinnecke** [comment]
> duplicate in content assist.

Sorry, there is no duplicate entry in the content assist at all!

![bildschirmfoto 2015-02-10 um 22 25 34](https://cloud.githubusercontent.com/assets/3775170/6136759/c3fa9532-b173-11e4-98b0-c8e0aa5c8567.png)

and

![bildschirmfoto 2015-02-10 um 22 26 25](https://cloud.githubusercontent.com/assets/3775170/6136770/e1c9ba02-b173-11e4-9f92-c1d6aef5e185.png)

This duplication is just inside the internal list of possible words for the syntax highlighter and invisible for the user.

**Comment by tthuem** [comment]
Fine!

**Comment by pinnecke** [comment]
:)

**Comment by pinnecke** [comment]
Because it seems that those red-green-yellow tristate system of the dialogs header does confuse the people, I replaced this images with standard behavior.

### Normal information
Such as starting information or if everything is fine doesn't have a image any longer. This state is if the dialog is *opened* or *syntax-check and all tests are okay* or *syntax-check is passed an tests are running*. The **OK-Button** is **enabled**.
![bildschirmfoto 2015-02-10 um 22 51 08](https://cloud.githubusercontent.com/assets/3775170/6137201/522fe91c-b177-11e4-9a9a-8439a4689910.png)

### Error message
If (and only if) the constraint text contains syntax error, the **OK-Button** is **disabled** and the image is an *error-symbol*

![bildschirmfoto 2015-02-10 um 22 50 53](https://cloud.githubusercontent.com/assets/3775170/6137197/49c3ba4c-b177-11e4-9288-310a45d5dc2e.png)

### Warning information
When typing a text into the constraint editor and this text is correct in syntax (in sense of constraints), as long as all checks are running in background, there is the **Normal information** state. If now one check fails (e.g. dead features), this state changes to *warning state*. Here, a warning image is shown but the **OK-Button** is enabled.

![bildschirmfoto 2015-02-10 um 22 50 15](https://cloud.githubusercontent.com/assets/3775170/6137190/3e344ff2-b177-11e4-877e-1c365789ad19.png)

**Comment by pinnecke** [comment]
## Changed position of buttons in dialog

![bildschirmfoto 2015-02-10 um 23 07 10](https://cloud.githubusercontent.com/assets/3775170/6137479/96b32f20-b179-11e4-87b7-6f66f83b5722.png)

**Comment by pinnecke** [comment]
Changed *Contains contains* to *Constraint contains* (see screenshot above)

**Comment by pinnecke** [comment]
Removed the possibility to add a line break by hitting **ENTER** into the constraint text. This is done with ```SWT.SINGLE```flag. Unfortunately this implies that the edit field **cannot handle**

* line breaks (text wrap) or 
* vertical scrolling

That means a large constraint which does not fit into the border of the text field have to be scrolled horizontal.

**Comment by pinnecke** [comment]
> The content proposal does not open in some cases (e.g. empty text field). When pressing STRG+SPACE nothing happens. 

That's because our current content proposal adapter is triggered with a so called *ActiviationDelayTime* (which is set to 500ms). There is no direct way to open it immediately, such as ```adapter.show```because there is no such method. When getting the underlying control via ``adapter.getControl()`` there's the method ``setVisible(boolean)`` but the proposal does not response. I tried to re-instanciate it, but this leads to a lot of parallel opened adapter windows. Currently we use Eclipse SWT ContentProposalAdapter default behavior, which opens the proposal when *ActiviationDelayTime* passed and there is something to show.

**Comment by pinnecke** [comment]
> If the user just clicks on an entry inside the proposal the caret moves to the begin of the just added text.

That's a bug.

**Comment by pinnecke** [comment]
> Sometimes there are line breaks insert into the text field

This could not be happen anymore (see above)

**Comment by pinnecke** [comment]
> The proposal does popup if entering a single space.

That's because it seems that this Eclipse control is triggered over text change action. Therefore insertion of a single space triggers the popup.

> Sometimes even further

Currently the popup does only open if triggered by keystrokes or Ctrl+Space hotkey. When inserting elements from the feature name list, the proposal won't open.

**Comment by pinnecke** [comment]
> The proposal popup shows only proposals wich are prefixes of the current input. Hence, a single feature name with length *1* such as *A* won't be shown. How can I be sure that this feature name exists?

If the input is already a valid feature name, the proposal shows only postfixes to complete to another known feature name (where the current input is a prefix). This makes sense because the feature is already typed into the textbox. However, it is possible to choose every feature name when starting with *white space* or by hitting *Ctrl+Space*. If the constraint text contains a feature name which is unknown, the syntax highlighter will underline the constraint.

![bildschirmfoto 2015-02-11 um 01 01 14](https://cloud.githubusercontent.com/assets/3775170/6139238/8cff8df6-b189-11e4-971b-6e3f59ec4e9c.png)

**Comment by pinnecke** [comment]
# Solution overview

* Added support for whitespace containing feature names such that they will be accepted and not marked as wrong words	
* Selecting and double clicking on white-space-containing features in the feature list will add them surrounded by quotes to the input textfield
* Automatically adding of quotes for "Create Constraint starting with "X"" option if X contains whitespaces
* Changed images for different dialog states to Eclipse-Standard-Behavior
* Removed the possibility to add a line break by hitting ENTER into the constraint text
* Some little grammar issues fixed
* Should fixed a bug which leads to only showing "not" and feature names in proposal when the first feature name is too short (maybe have a further look at this bug)
* Added Ctrl+Space to open the proposal dialog (which seems conflicting to automatic opening)
* Reimplemented some logic to handle insertion of text from proposal correctly if nothing was given in assigned text field


Those changes are in remote branch **issue_210_mp** please check it.

**Comment by tthuem** [comment]
Code Review
----------------------------------

Second statement seems to be unnecessary:

``` Java
bubble = new Label(headComposite, SWT.NONE | SWT.TOP);
bubble.setImage(null);
```

"Your constraint voids the model" sounds wrong. Please use constants at the beginning of the file and I'll go through all of them again and correct them, if necessary. Also, the capitalization is not consistent.

Finally, some variable names have not been updated:

``` Java
public static final Image IMAGE_CIRCLE_YELLOW = FMUIPlugin.getImage("message_warning.gif");
public static final Image IMAGE_CIRCLE_RED = FMUIPlugin.getImage("icon_error.gif");
```

Manual Testing
--------------------------------

The content assist does always add the content to the end, even when used somewhere in the middle of the constraint. The following examples show the result of adding not before the last feature name. First with no letters typed, second with some letters already typed:

![contentassist-middle1](https://cloud.githubusercontent.com/assets/5330357/6154648/98154da8-b22d-11e4-81a4-5dca9685fa79.png)
![contentassist-middle2](https://cloud.githubusercontent.com/assets/5330357/6154649/9a9a7864-b22d-11e4-9edd-e476469160ad.png)
![contentassist-middle3](https://cloud.githubusercontent.com/assets/5330357/6154651/9f07c2d0-b22d-11e4-9396-35395ac0cb1a.png)
![contentassist-middle4](https://cloud.githubusercontent.com/assets/5330357/6154655/a29aa872-b22d-11e4-838c-c8bdcf617bef.png)

Typing the start of a feature name with white spaces without " at the beginning leads to weird result.

![whitespace1](https://cloud.githubusercontent.com/assets/5330357/6154789/aca0399e-b22e-11e4-85bb-aa675c64eeb4.png)
![whitespace2](https://cloud.githubusercontent.com/assets/5330357/6154791/ae5664e8-b22e-11e4-8925-3c04b469ff1a.png)

When having a feature model with white spaces, all features without white spaces are not shown in content assist and operators are missing, too.

![missingfeatures](https://cloud.githubusercontent.com/assets/5330357/6154810/cd752ecc-b22e-11e4-9b16-6660cb35daee.png)

It is unintuitive that the text field has several rows, but linebreaks are impossible.

Just a remark. It seems that brackets are just shown everywhere, even though an opening bracket can only occur at the beginning or after a binary operator. Similarly, the closing bracket can only occur after a feature name. But could be added to software projects tasks.

Sorry, that's again a quite long list of things. Nevertheless, I experienced that many things work much better already. :)

**Comment by pinnecke** [comment]
> Second statement seems to be unnecessary:

Removed all obsolete references and variables (see remote **issue_210_mp** commit **6ad4638**).

>  "Your constraint voids the model" sounds wrong. Please use constants at the beginning of the file and I'll go through all of them again and correct them, if necessary. Also, the capitalization is not consistent.
>  Finally, some variable names have not been updated:
> ...

I moved all the text to a so called ```StringTable```, here so can change the text all at once (see remote **issue_210_mp** commit **c92530c**)
``` Java
static class StringTable {
		static final String CHECK_STARTED = ...
		...
}
```

**Comment by pinnecke** [comment]
> It is unintuitive that the text field has several rows, but linebreaks are impossible.

Removed that.

> Just a remark. It seems that brackets are just shown everywhere, even though an opening bracket can only occur at the beginning or after a binary operator. Similarly, the closing bracket can only occur after a feature name. But could be added to software projects tasks.

That's clearly true, because I do not limit the "(" and ")" "Operator" in the proposal. However, should I move this task so software project?

**Comment by pinnecke** [comment]
Just for testing performance impact of feature model size: The following code produces a model like this to a given level *level*.
![bildschirmfoto 2015-02-19 um 17 45 29](https://cloud.githubusercontent.com/assets/3775170/6271151/23e9f086-b85f-11e4-9d5c-9f8016b7f0f7.png)


``` Java
public final class ModelBuilder {
		
		public final String build(int level) {
			String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>"
					+ "\n<featureModel chosenLayoutAlgorithm=\"1\">"
					+ "\n<struct>%s"
					+ "\n</struct>"
					+ "\n<constraints/>"
					+ "\n<calculations Auto=\"true\" Constraints=\"true\" Features=\"true\" Redundant=\"true\" Tautology=\"true\"/>"
					+ "\n<comments/>"
					+ "\n<featureOrder userDefined=\"false\"/>"
					+ "\n</featureModel>";
			
			for (int i = 0; i < level; i++)
				xml = grow(xml, i);
			
			return xml.replace("%s", "");
		}
		
		private final String grow(final String xml, final int i) {
			final String inner = "\n<and abstract=\"true\" mandatory=\"true\" name=\"R#NUM\">"
					+ "\n<and abstract=\"true\" name=\"A#NUM\">"
					+ "\n<feature mandatory=\"true\" name=\"C#NUM\"/>"
					+ "\n<feature name=\"D#NUM\"/>"
					+ "\n<feature name=\"E#NUM\"/>"
					+ "\n<feature name=\"F#NUM\"/>%s"
					+ "\n</and>"
					+ "\n<or mandatory=\"true\" name=\"B#NUM\">"
					+ "\n<feature mandatory=\"true\" name=\"G#NUM\"/>"
					+ "\n<alt mandatory=\"true\" name=\"H#NUM\">"
					+ "\n<feature mandatory=\"true\" name=\"I#NUM\"/>"
					+ "\n<feature mandatory=\"true\" name=\"J#NUM\"/>"
					+ "\n</alt>"
					+ "\n</or>" + "\n</and>";
			return String.format(xml, inner.replace("#NUM", String.valueOf(i)));
		}
		
	}
```
I use this to check those performance issues and also some ConstraintDialog problems (e.g. does "Dead Features" are listened correct). However, the code snippet above could be useful in other cases. Where should I store it?

**Comment by pinnecke** [comment]
> Manual Testing: The content assist does always add the content to the end, even when used somewhere in the middle of the constraint. The following examples show the result of adding not before the last feature name.

Indeed, this doesn't work very well currently. The problem is, that the default behavior of the SWT proposal won't move the caret correctly if accepting a proposal directly, e.g. ```Feature |``` with acceptation of ```and``` will lead to ```Feature |and``` instead of expected ```Feature and|```. However, this behavior can be implemented but unfortunately this is "all-or-nothing" which means, adding the expected behavior above overwrites all the over text changes for a given accepted proposal. I will reimplement the functionality plus the one above and test those accordingly (see ```de.ovgu.featureide.fm.ui.editors.ContentProposalActionTest``` in ```de.ovgu.featureide.fm.ui-test``` project). 

The next table shows you a given input, the accepted proposal and what is expected to be the result. Please note: This test focus on the text change functionality rather than the proposal list itself (for this, see ```de.ovgu.featureide.fm.ui.editors.ConstraintContentProposalProviderTest``` in ```de.ovgu.featureide.fm.ui-test``` project). 

The pipe **|** displays the current caret position inside the text whereas two pipes *A|BC|D* means a selection of e.g. *BC*.

Input 								| Accepted Proposal 	| Resulting text
------------------------------------|-----------------------|------------------
"\|"    								| FeatureA   			| "FeatureA\|"
"\|  "    							| FeatureA    			| "FeatureA\|  "
"  \|"      							| FeatureA    			| "  FeatureA\|"  
"  \|  "      							| FeatureA    			| "  FeatureA\|  "
"A \|"    							| and    				| "A and\|"
"A \| "     							| and    				| "A and\| " 
"  A \|"      						| and    				| "  A and\|"  
"A and \|B"    							| B    				| "A and B\|"
"A and \|b"    							| B    				| "A and B\|"
"Feature \|"    						| and    				| "Feature and\|"
"Feature \| "     					| and    				| "Feature and\| " 
"  Feature \|"     					| and    				| "  Feature and\|"  
"  Feature \|  "     					| and    				| "  Feature and\|  "  
"A and \| B"    						| not    				| "A and not\| B"
"A and \|B\|"    						| C    					| "A and C\|"
"feature\|"    						| FeatureA    			| "FeatureA\|"
"Feature\|A\|"    					| FeatureB    			| "FeatureB\|"
"fea\|ture\|"    						| FeatureB    			| "FeatureB\|"
"|Feat|ureA"    						| FeatureB    			| "FeatureB\|"
"not Elevator and \| TwoThirdsFull"   | not    				| "not Elevator and not\| TwoThirdsFull"
"not Elevator and n\| TwoThirdsFull"  | not    				| "not Elevator and not\| TwoThirdsFull"
"not Elevator and no\| TwoThirdsFull" | not    				| "not Elevator and not\| TwoThirdsFull"

Do I miss an important case here? Please add and/or comment!

**Comment by pinnecke** [comment]
It's now available in remote branch **issue_210_mp**. Please review.

**Comment by pinnecke** [comment]
If the feature model contains features which are operator names (e.g. feature "not"), the proposal adds now the suffix "(Feature)" to the feature in order to avoid confusion between the *not*-Operator and *not*-Feature. However, this suffix is just for information and will not be copied into the input text control. Now, if a feature is a operator name or if a feature contains white spaces, they will be automatically surrounded with braces. This also hold if a user clicks on a feature *A* in feature model and then to pop up menu item "Create Feature starting with *A*".

![bildschirmfoto 2015-02-25 um 12 07 23](https://cloud.githubusercontent.com/assets/3775170/6369482/191ade72-bce7-11e4-943a-6c4757026f47.png)

![bildschirmfoto 2015-02-25 um 12 09 58](https://cloud.githubusercontent.com/assets/3775170/6369495/376fea5c-bce7-11e4-81d6-1ea3b86a57e8.png)

**Comment by pinnecke** [comment]
## Bug with re-opening constraints

When storing the constraint above
![bildschirmfoto 2015-02-25 um 12 09 58](https://cloud.githubusercontent.com/assets/3775170/6369543/be420e16-bce7-11e4-8829-817b7c3b8b9b.png)

 the feature model updates correctly.

![bildschirmfoto 2015-02-25 um 12 10 49](https://cloud.githubusercontent.com/assets/3775170/6369523/93b27ea6-bce7-11e4-83c4-9c9f92bc4ff3.png)

If editing this constraint the "text" for the dialog is 

![bildschirmfoto 2015-02-25 um 12 13 42](https://cloud.githubusercontent.com/assets/3775170/6369538/b3ca830a-bce7-11e4-80e0-7f17355578d0.png)

**Please note, that the quotes are missing**. That's problematic because a well-formed constraint from the past is now not well formed anymore (because the quotes are missing).

**Comment by pinnecke** [comment]
Solved **Bug with re-opening constraints** by adding a "pretty printer" ```String de.ovgu.featureide.fm.core.Constraints.autoQuote(Constraint)``` inside a (new) constraint helper class ```Constraints``` which automatically surrounds features as described above with quotes.

![bildschirmfoto 2015-02-25 um 13 20 59](https://cloud.githubusercontent.com/assets/3775170/6370461/19ec7338-bcf1-11e4-9b2b-68e0b852450e.png)

See ```de.ovgu.featureide.fm.core.ConstraintToStringTest``` for further tests in this direction.

**Comment by pinnecke** [comment]
Changes are now public in remote branch **issue_210_mp**. Please note, that the content proposal filter functionality is still buggy and disabled for now. Which means each operator and each feature is available at any time, currently.

**Comment by tthuem** [comment]
> However, should I move this task so software project?

Yes.

> However, the code snippet above could be useful in other cases. Where should I store it?

There is already a generator for feature models within FeatureIDE, which you could have used: https://github.com/tthuem/FeatureIDE/blob/master/plugins/de.ovgu.featureide.fm.core/src/de/ovgu/featureide/fm/core/editing/evaluation/Generator.java If you think this snippet is still useful, you could add it in the same package.

**Comment by pinnecke** [comment]
Opened new comment with related description in #178 for software project.

**Comment by pinnecke** [comment]
> There is already a generator 
This class is fine! There's no need for another one to my mind.

**Comment by tthuem** [comment]
Found two bugs.

1. Opening a constraint with a feature name that has a whitespace does not work:

![bug](https://cloud.githubusercontent.com/assets/5330357/6419527/522efd14-bebe-11e4-810c-77bef66fd29a.png)

2. False-optional feature is detected for the following feature diagram, but not within the constraint dialog already:

![bug2](https://cloud.githubusercontent.com/assets/5330357/6419548/718dffde-bebe-11e4-92dc-1df8bf43ff5c.png)

Please fix these two bugs and merge it into the master. I really need to create the new version on Monday and the current master is quite unstable with respect to the constraint dialog.

**Comment by pinnecke** [comment]
> A. Opening a constraint with a feature name that has a whitespace does not work:
Fixed, see remote branch **issue_210_mp**.

**Comment by pinnecke** [comment]
> False-optional feature is detected for the following feature diagram, but not within the constraint dialog already

Looks to my as this is a very old bug. I could reproduce the bug and figured out, that for the first time the false-optional-check is done, it is correct. Afterwards already check features were ignored. I found the reason in the false-optional-calculation itself (the lines which are commented out by me, solve the bug):

```Java
private List<Feature> getFalseOptional(String input, FeatureModel model) {
		List<Feature> list = new ArrayList<Feature>();
		FeatureModel clonedModel = model.clone();

		NodeReader nodeReader = new NodeReader();

		Node propNode = nodeReader.stringToNode(input, clonedModel.getFeatureNames());

		for (Feature feature : model.getFeatures()) {
			if (input.contains(feature.getName())) {
				//if (feature.getFeatureStatus() != FeatureStatus.FALSE_OPTIONAL) {
					clonedModel.addPropositionalNode(propNode);
					clonedModel.getAnalyser().analyzeFeatureModel(null);
					if (clonedModel.getFeature(feature.getName()).getFeatureStatus() == FeatureStatus.FALSE_OPTIONAL && !list.contains(feature))
						list.add(feature);
				//}
			}
		}

		return list;
	}
```

As I see it, you store the status of a feature inside the feature itself. However, this leads to negative false-optional-check although it should be positive because required features are skipped. However, if those two commented lines are not necessary the problem should be fixed, see remote branch **issue_210_mp**


![bildschirmfoto 2015-02-28 um 20 13 53](https://cloud.githubusercontent.com/assets/3775170/6427632/47fd2be0-bf86-11e4-9851-f5b456fcd6a3.png)

**Comment by pinnecke** [comment]
Please review and merge into master, see **issue_210_mp**

**Comment by tthuem** [comment]
Seems to work fine now. :)

**Comment by tthuem** [comment]
Merged
