### ISSUE TITLE
Problems with umlauts in feature names that occur in configurations

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#212]
Opened Desktop-Searcher example and renamed feature Windows to Windowsö. While the feature is correctly renamed in the configurations, these are marked as invalid afterwards. The reason seems to be a problem with text encoding:

![bug-umlaut](https://cloud.githubusercontent.com/assets/5330357/6153585/ec1f7778-b225-11e4-96fc-4089493cb4f6.png)

Do we use a wrong encoding when reading/parsing the configuration file? It there is no easy fix, we could forbid umlauts in feature names as for Antenna. (see #170)

**Comment by tthuem** [comment]
Same problem occurs for all composers and even when selecting the feature manually and saving the configuration again. It seems that reader and writer rely on a different charset.

**Comment by skrieter** [comment]
I fixed the wrong warning in the configuration files by providing the UTF-8 charset for every saved configuration file.
However, both composeres, ahead and featurehouse seems to have problems with parsing feature names containing umlauts.
I think the best solution is to forbid umlauts for these composeres.

**Comment by tthuem** [comment]
Marcus, what do you think of Sebastian's proposal? Can you do this until Monday?

**Comment by pinnecke** [comment]
As far as I understood thats related to #210. Should be already restricted for all composers in that branch. But there is something like context loss, see #210. However, I can complete this depending on the solution to that. I already assigned Sebastian to #210 in order to find the quickest possible fix.

**Comment by pinnecke** [comment]
Restriction for composer are now available in #210 branch.
