### ISSUE TITLE
Update Wiki for new behavior of ConstraintDialog

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#213]
In order to keep up-to-date, update the Feature IDE wiki with the new updates since several changes in the past.

**Comment by pinnecke** [comment]
For Testing Instructions, see [Wiki Page Testing Instructions](https://github.com/tthuem/FeatureIDE/wiki/Testing-Instructions-for-the-ConstraintDialog)

For a user guide to the constraint dialog, see [the according wiki page](https://github.com/tthuem/FeatureIDE/wiki/Constraint-Editing-and-the-Constraint-Dialog)

Please review and close issue if everything is okay.

**Comment by tthuem** [comment]
Looks great.
