### ISSUE TITLE
32bit/64bit Version of FeatureIDE VS. 64bit Java

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#214]
I have downloaded the prepared version of FIDE from the website. Its indicated as usable for 32 and 64bit. 
On my 64bit Windows 7 system i have installed the 64bit version of java. Eclipse is causing an error at startup, Error 13.

First try to fix this error was to install the java 32bit version also. Eclipse starts successfully.

The prepared version is may be used on 64bit system but you have to use 32bit java. this should be noted on the website.

**Comment by tthuem** [comment]
Changed the website accordingly.
