### ISSUE TITLE
General usablity - FeatureIDE nature in prepared version

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#215]
The prepared version from the website doesn't show the FIDE perspective by default. Is it possible to change the setup? As a FIDE user, i would expect to have this setting by default.

**Comment by tthuem** [comment]
I don't know how. Anyone else?

**Comment by pinnecke** [comment]
Not for sure, but is the perspective not directly set by the user? http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-31.htm

**Comment by tthuem** [comment]
As far as I know, the only option would be to ask the user whether our perspective should be opened when opening a certain file (similar to AspectJ). However, this can be annoying and it does not help in the first place (e.g., empty workspace and creating a new FeatureIDE project). Therefore, we ship the zip file with a default workspace in which the perspective is enabled.
