### ISSUE TITLE
General usablity - FIDE default workspace setting

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#216]
The downloable version uses a default workspace C:\users\tthuem... or something similar. We should change that, maybe to have it as a relative path. The archive from the website has this relative folder, but doesn't seem to use it.

**Comment by ckruczek** [comment]
Tried this with the linux version 3.6 x86_x64  and the same error occured here but with a different workspace path 'home/soenke/Downloads/FeatureIDE_linux_x86_64/workspace'.

**Comment by tthuem** [comment]
The problem is that once you started Eclipse it will store the last workspace. If you tell me how to remove it, I can do it for the next version.
