### ISSUE TITLE
General usablity - Renaming of src folder based on config name

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#217]
The src folder uses the naming scheme "src/CONFIGNAME". After deleting a config file, one the remaining configs is used an the name of the src folder is change correctly. If i delete the last config file the src folder keeps the last name and is not changed back to default or something similar.

**Comment by tthuem** [comment]
There is no easy solution for now and we should rather try to change FeatureHouse to use src as an output folder instead of src/CONFIGNAME.
