### ISSUE TITLE
General usablity - FeatureHouse full build necessity

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#218]
Currently we change the full version of berkeleydb (c) to have no parsing error caused by the c-grammar in featurehouse. After changing one file or one every save while the development, FIDE performs a full build. This behavior removes all error markers, so the user has to wait until the build is done an all error markers are added to the packeage explorer an the editor itself. This takes much time also. Is it necessary to perform a full build every time?

**Comment by andykenner** [comment]
the used berkeleydb version has 419 files. All files are used in the full build?

**Comment by meinicke** [comment]
dulplicate #9
