### ISSUE TITLE
Constraint dialog allows users to edit the feature diagram in parallel but does not listen to changes

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#219]
Opened a feature diagram, edited an existing constraint, and changed the feature diagram (renamed feature, added/removed feature). The result is that the constaint dialog is out of sync and unusable. The safest solution would be to simply make the constraint dialog a UI blocking dialog.

**Comment by meinicke** [comment]
As Thomas said, just block the UI,like other dialogs/wizards do. It is to much effort to sync the dialog with the editor.

**Comment by pinnecke** [comment]
See issue_219 on remote, please check that this solves the issue. Finally please merge.

**Comment by skrieter** [comment]
Merged.
