### ISSUE TITLE
Internal Error for calculation of statistics

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#225]
For the project https://github.com/DB-SE/isp2014.anton.anders/tree/master/Aufgabe3, opening the statistics view creates an error popup:

An internal error occurred during: "Calculate de.ovgu.featureide.ui.statistics.core.composite.lazyimplementations.DirectivesNode".
Index: 0, Size: 0

**Comment by pinnecke** [comment]
I tested the statistics view on the hello world antenna example. This works fine.

Unfortunately opening the statistics view on **Hello World DeltaJ** and **Hello World Colligens** and **Hello World Android** the warning dialog

``An internal error occurred during: "Updating FeatureStatisticsView".
java.lang.NullPointerException ``

occurs.

**Comment by pinnecke** [comment]
However, the problem only occurs iff a source file does not contain any #ifdef symbol which means this source file does not play a role. Consequently if the statistics calculator tries to figure out which role the class plays it fails (because there is no role). This is the reason for the index out of bounds which leads to that message. Solution: Catch this case and proceed.

**Comment by pinnecke** [comment]
Merged this directly into master. Please check, if the calculations are still correct (which should be). As far as I can see, this is fix only touches antenna project. Finally please close this issue.

**Comment by pinnecke** [comment]
Hi Sebastian, I looked at the diff. Looks good. Please merge and close.

**Comment by skrieter** [comment]
Fixed.
