### ISSUE TITLE
Export of Feature Model as SVG not working

### ISSUE THREAD

**Issue by kruegers** [tthuem/FeatureIDE#227]
Steps to reproduce:
* Open feature model in featue model editor.
* Rightclick in the editor and select "Export As".
* Select svg as file format and enter some filename.
* Press save button.

There is no file created regardless of which path and filename I enter. For other file formats (such as png), the export works fine however. 
I use Eclipse Juno, my FeatureIDE version is the current master branch and I use the ImageExport plugin from veger in the version they currently provide on their update site.

**Comment by tthuem** [comment]
Does this happen on any model? Have you looked into the error log for details?

**Comment by kruegers** [comment]
Initially, I wanted to export a model from a FeatureHouse project. For testing, I also tried models of Antenna, FeatureC++ and Munge and all exports failed. 
Error Log isn't containing anything regarding this export or its failure. My first guess is that some class or method in the ImageExport plugin was "refactored" and the respective call from FeatureIDE via Java Reflections doesn't get any result but I'm not sure.
