### ISSUE TITLE
Existing workingsets are not usable in dialog New FeatureIDE Project

### ISSUE THREAD

**Issue by andykenner** [tthuem/FeatureIDE#232]
Adding a new FeatureIDE project to a given workingset ist not possible. If the option "add project to working sets" is use, the existing ones are not accessible in the dropdown box and not shown in the detailed working set selection dialog

![image](https://cloud.githubusercontent.com/assets/8641920/6823855/8615e07e-d2ec-11e4-8986-c5b7b4416e0d.png)

A working set beside other projects is existing.

**Comment by meinicke** [comment]
call existing wizards (e.g., Java, C)

**Comment by skrieter** [comment]
Can be fixed as part of issue #12.
