### ISSUE TITLE
Adding an additional feature model file does not refresh the package explorer

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#235]
When adding a new feature file (other than the existing <code>model.xml</code), the package explorer is out of sync until manually refresh.

**Comment by pinnecke** [comment]
Fixed this in remote branch **issue_235** by refreshing all current projects in package explorer (current project reference was always NULL?). Better solution (?) and review ;)

**Comment by meinicke** [comment]
do not refresh the whole workspace, this might cause unpredictable sideeffects (e.g., other projects build)
why dont you just refresh the new file? See FeatureProject.java
