### ISSUE TITLE
Fix deprecated plug-in problems

### ISSUE THREAD

**Issue by fbenduhn** [tthuem/FeatureIDE#24]
Since Juno: Elements: 'action' and 'objectContribution' ExtensionPoint?: 'org.eclipse.ui.popupMenus'

**Comment by pinnecke** [comment]
As far as I can see, the entire _action framework is deprecated_. There's a replacement called *Command Framework*. For a tutorial see http://blog.eclipse-tips.com/2009/01/commands-part-1-actions-vs-commands.html

**Comment by tthuem** [comment]
The warnings indeed disappeared, but I got compiler errors in the test fragment de.ovgu.featureide.core.ahead-test. What is the problem?

**Comment by tthuem** [comment]
The problem was that that you created a new project, but the .project file was not added due to a bug in the gitignore.

**Comment by tthuem** [comment]
Did not get a single warning. :)
