### ISSUE TITLE
Constraint dialog truncates part of the constraint during opening

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#243]
Again, a problem with the new constraint dialog, unfortunately. Long constraints are not opened properly:

![bug1](https://cloud.githubusercontent.com/assets/5330357/7319255/78f63532-ea94-11e4-8c35-068ad0cd921e.png)

![bug2](https://cloud.githubusercontent.com/assets/5330357/7319258/7a96a368-ea94-11e4-8236-f453c3d215d9.png)

**Comment by pinnecke** [comment]
Actually, this was a bug in internal ConstraintDialog, which was confused with the "not". However, I fixed this in remote branch **issue_243** and added tests which cover this bug. Additionally, all other tests related to ConstraintDialog run fine. 

Please check, comment and merge.

**Comment by tthuem** [comment]
Seems to work fine. Please go ahead and merge it.
