### ISSUE TITLE
Feature Model Outline is unavailable if model file is not names "model.xml"

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#245]
Since in `Outline.java`, the mode is selected depending on the model file name "model.xml", a feature model from a feature model xml file unequal to "model.xml" will not be supported by feature model outline.

``` Java
447: if ("model.xml".equals(file.getName())) {
448: 	selectedOutlineType = OutlineLabelProvider.OUTLINE_FEATURE_MODEL;
```

![bildschirmfoto 2015-04-30 um 00 30 19](https://cloud.githubusercontent.com/assets/3775170/7402839/4086995e-eed0-11e4-9f8c-407cbc5569c8.png)

![bildschirmfoto 2015-04-30 um 00 30 46](https://cloud.githubusercontent.com/assets/3775170/7402833/34af7e34-eed0-11e4-9111-45fea0d83385.png)

**Comment by pinnecke** [comment]
See remote branch **issue_245**. Please review and merge into master.

**Comment by skrieter** [comment]
Merged.
