### ISSUE TITLE
New featureide file wizard selects haskell as default

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#247]
The wizard should remember the last selection and should select this file type when creating a new file.

**Comment by tthuem** [comment]
Sounds like something for software project. Jens, do we want to move it to that milestone and unassign Sebastian?

**Comment by meinicke** [comment]
No. The bug is really annoying and should be only a matter of minutes for Sebastian.

**Comment by skrieter** [comment]
Don't fight over it, it's already fixed :)

**Comment by tthuem** [comment]
:)
