### ISSUE TITLE
Literal appears as Or with only 1 children when using NodeCreator.createNodes

### ISSUE THREAD

**Issue by garganti** [tthuem/FeatureIDE#253]
When I analyze the following model (with false optionals)
![cattura](https://cloud.githubusercontent.com/assets/1856220/7677736/ef9c1d6a-fd4e-11e4-9b58-33b36311224c.PNG)
and convert to Nodes, I get wrong types for the literals.
If I call: 
Node ffm = NodeCreator.createNodes(fm,false);
System.out.println(ffm);
I get 
WORLD  &  BYE  &  True  &  - False  &  (WORLD  |  BYE  |  True)
If I call:
Node node0 = ffm.getChildren()[0];
System.out.println(node0); --> WORLD  &  BYE
System.out.println(node0.getChildren()[1]); --> BYE
System.out.println(node0.getChildren()[1].getClass()); --> class org.prop4j.Or
but I was expecting a Literal.
I don't know how to treat an Or with only one children (Should I consider it as a Literal)? 

I have written the following test case:
@Test
public void testImportfIDEFault() throws FeatureModelException, UnsupportedModelException, IOException {
FeatureModel fm = new FeatureModel();
AbstractFeatureModelReader reader = new XmlFeatureModelReader(fm);
reader.readFromFile(new File("Example1_FAULTY.xml"));
Node ffm = NodeCreator.createNodes(fm,false);
System.out.println(ffm);
Node node0 = ffm.getChildren()[0];
assertEquals("BYE", node0.getChildren()[1].toString());
assertEquals(Literal.class, node0.getChildren()[1].getClass());		
}
which fails.
Thanks
Angelo

**Comment by meinicke** [comment]
Can someone look at the patch, I think that the simplify method requires some refactoring as it is not understandable anymore!


class NodeCreator {
...
private static Node simplify(Node node) {
		if (node instanceof Literal) {
			Literal lit = (Literal) node;
			if (lit.var.equals(varFalse) && !lit.positive)
				return new Literal(varTrue);
			if (lit.var.equals(varTrue) && !lit.positive)
				return new Literal(varFalse);
			return lit;
		}
		Node[] children = node.getChildren();
		**if (children.length == 1 && node instanceof Or) {
			return children[0];
		}**

...
