### ISSUE TITLE
Find/Search for feature-model editor

### ISSUE THREAD

**Issue by joliebig** [tthuem/FeatureIDE#258]
a find/search method for the feature-model would be extremely helpful for navigation. Is neither available in the "edit" menu nor the context menu.

**Comment by skrieter** [comment]
Currently there are two ways to search for features in the diagram editor.
  1. You can select the feature in the feature model outline. If the diagram editor is open it should focus on the selected feature.
  2. In the diagramm editor you can simply type the feature name and the editor window should jump to the next feature with a matching feature name prefix. (The behavior is very similar to the Windows Explorer)

Hope, this helps for the moment.
There may be more sophisticated ways of searching features in the future.

**Comment by joliebig** [comment]
Both ways are very helpful. Thanks.
