### ISSUE TITLE
ConstraintDialog does not close if Constraint is not satisfiable

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#262]
If a constraint is not satisfiable, the constraint dialog does not close since during the closing the dialog is already disposed when the according error message should be displayed.

**Comment by pinnecke** [comment]
Issue was cursed by legacy code. When closing the shell, several checks run and may display some error messages. Since this checks are obsolete with the current functionality of the constraint dialog, I removed the related code.

**Comment by pinnecke** [comment]
Please review, check and merge into master. Remote Branch: **issue_262**

**Comment by skrieter** [comment]
Merged.
