### ISSUE TITLE
LegendFigure.java performance improvements

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#263]
Commit 8ca0bed58ca4eb2a80760748534757317666dc13 introduces some changes to improve the legend figure performance (e.g. by caching states). Since this commit introduces a bug related to displaying the legend (see https://github.com/tthuem/FeatureIDE/issues/230), I reverted <code>LegendFigure.java</code> to its state before in order to solve https://github.com/tthuem/FeatureIDE/issues/230. However, this might affect the legend figure performance. Please check and improve the performance, if necessary.

**Comment by skrieter** [comment]
Fixed, see #266.
