### ISSUE TITLE
collaboration diagram search dialog opens for CTRL+(any key)

### ISSUE THREAD

**Issue by meinicke** [tthuem/FeatureIDE#267]
- set the focus to the collaboration diagram
- press CTRL+(any key)
- the dialog opens

The dialog should only open if CTRL+f

**Comment by ckruczek** [comment]
Since https://github.com/tthuem/FeatureIDE/issues/181 there was no defined concept how the search dialog should be triggered. For the moment any key-stroke inside the collaboration diagram triggers the search dialog. Maybe we need to discuss this further.

**Comment by fheyden** [comment]
Fixed if-condition - Dialog only opens with ctrl-f now.

**Comment by pinnecke** [comment]
Works for me. Please remove commented line 86 in file `CollaborationViewSearch.java` and merge into master
