### ISSUE TITLE
Duplicated string DEF in collaboration diagram

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#273]
Collaboration diagram shows duplicated string "ifdef def" for https://github.com/TUBS-ISF/spl2015.christopher.sontag/tree/master/Christopher-Sontag-Task3

![zwischenablage-3](https://cloud.githubusercontent.com/assets/5330357/8409565/f78fd3ae-1e78-11e5-8a16-b5a825165a63.png)

Major because it is annoying when one wants to create screenshots for a paper or so.

**Comment by meinicke** [comment]
fixed in https://github.com/tthuem/FeatureIDE/commit/3b9be55fafe40a9f7b22b7b2d56e660a19bde03f
