### ISSUE TITLE
Statistic on (number of features in) directives wrong

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#274]
All directives in the following project contain just a single feature but the statistics view reports between one and four features: https://github.com/TUBS-ISF/spl2015.alexander.knueppel/tree/master/Alexander-Knueppel-Task3

![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/8409903/38fec53c-1e7b-11e5-8f6d-a51acfebf48c.png)

It could be also that the data in the Collaboration Diagram is wrong, did not check that.

**Comment by tthuem** [comment]
Also found another example where the number is too low: https://github.com/TUBS-ISF/spl2015.jewgeni.rose/tree/master/jewgeni-rose-task3

![zwischenablage-5](https://cloud.githubusercontent.com/assets/5330357/8411441/4cfe89e2-1e84-11e5-8b1a-a4c4dcf1bfb3.png)

**Comment by meinicke** [comment]
Almost all calculated numbers seem to be wrong
see: number of directives, nesting...

**Comment by pinnecke** [comment]
Merged into master
