### ISSUE TITLE
Invalid request to open a file from a FeatureIDE project

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#276]
Seen this this behavior for several projects. However, it occurs sporadically.

https://github.com/TUBS-ISF/spl2015.henrik.lange/tree/master/Henrik-Lange-Task3

![zwischenablage-4](https://cloud.githubusercontent.com/assets/5330357/8411027/ffa1a1ea-1e81-11e5-834b-80a0eaa81a4f.png)

The content of collaboration diagram, statistics view and outline is not available. Refresh in collaboration diagram does not help.

**Comment by meinicke** [comment]
cannot be reproduced (maybe fixed in https://github.com/tthuem/FeatureIDE/commit/fddc1549987acdf66963d507d3cd84b0ad22b8cc)
