### ISSUE TITLE
Building Workspace FeatureHouse

### ISSUE THREAD

**Issue by Kogoro** [tthuem/FeatureIDE#280]
I encountered a problem with generating a new project with FeatureHouse as composer. When I klick on 'OK' and build a variant or all variants the message is shown up again.
Using:
Version: Luna SR2 (4.4.2)
Build id: M20150204-1700
FeatureIDE 2.7.3.201503041644
FeatureIDE extension for FeatureHouse (optional)	 2.7.4.201506171554
![error](https://cloud.githubusercontent.com/assets/8019776/8479473/510cbbf2-20d8-11e5-9d00-d80ca5b02934.png)

Okay while posting the versions of the plugins I realize i had an old version, after an update it is all okay. Sorry

**Comment by tthuem** [comment]
Seems to be reasoned by the different versions as discussed above.
