### ISSUE TITLE
Ctrl + Z (Undo Action) - Not working in Featuremodel-Configuration Editor

### ISSUE THREAD

**Issue by ckruczek** [tthuem/FeatureIDE#289]
### Prerequisites 
**Operating System** : Arch Linux
**Eclipse Version** :

     Eclipse for RCP and RAP Developers

     Version: Juno Service Release 2
     Build id: 20130225-0426

**FeatureIDE-Version**:  FeatureIDE  2.7.3.201503041644

### Bug description
When changing a configuration in the configuration editor and pressing Ctrl + Z to undo that action -> The changes are not undone and the configurations stays the same.

**Comment by tthuem** [comment]
There is simply no undo implemented for the configuration editor. You may add it to the software project topics, if you think it is helpful.
