### ISSUE TITLE
Feature Color ProfileManger performance is too slow

### ISSUE THREAD

**Issue by pinnecke** [tthuem/FeatureIDE#291]
* Improve ProfileManager Eclipse implementation of I/O interfaces
* Cache object

**Comment by tthuem** [comment]
What is a profile manager? Please tag related parts of FeatureIDE in this issue.

**Comment by meinicke** [comment]
I will revise this

**Comment by tthuem** [comment]
Colors of the feature-model diagram or colors assigned to features?

**Comment by meinicke** [comment]
fixed in SOPro Banch https://github.com/tthuem/FeatureIDE/tree/christianJonasBranch_squashed
