### ISSUE TITLE
Feature model editor hard to use without mouse

### ISSUE THREAD

**Issue by ckaestne** [tthuem/FeatureIDE#293]
There are various shortcuts to edit feature models without resorting to the mouse. Unfortunately, after every step the selection loses the focus, making it really inconvenient to edit. One spends more time navigating back to the same place than actually editing the thing.

(e.g., try to insert or delete a bunch of features in a row)

**Comment by tthuem** [comment]
Indeed, this bug is quite annoying and the lost focus seems to date back a year or so.
