### ISSUE TITLE
Whether configuration is valid or not is invisible when scrolling down

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#90]
(Reported by Sebastian Krieter.)

Instead, the statistics should be always visible and could be extended by showing the number of selected/deselected/undecided features in addition.

**Comment by tthuem** [comment]
Sebastian, if you have not yet started with this issue I would move it to as potential issue for the software project. Have you started?

**Comment by skrieter** [comment]
Fixed and merged into Master.
