### ISSUE TITLE
Improve performance of configuration editor

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#96]
Currently, automatic selections are calculated for all features whenever a feature is deselected or selected. In this time, the editor and Eclipse freezes. Instead, calculate automatic values only for visible features synchronous and for invisible features asynchronously.

Scrolling may be supported in a first step, by just showing a different symbol for non-updated features and may later on be improved by prohibiting their selection and deselection. Furthermore, newly visible features may be scheduled next and updated as soon as their are calculated.

**Comment by pinnecke** [comment]
Should be solved with branch **issue_26** see #26, isn't it?

**Comment by skrieter** [comment]
Done, merged Master.
