### ISSUE TITLE
Improve performance of constraint dialog

### ISSUE THREAD

**Issue by tthuem** [tthuem/FeatureIDE#97]
Currently, the editor simply freezes as far as the user types something. Distinguish between fast syntactical checks and slow semantic checks. Semantic checks may only be done when pressing OK, or with an extra button. In addition, check that it scales up-to thousands of features; we may remove some checks completely (e.g., regarding redundant constraints).

**Comment by pinnecke** [comment]
Pushed to remote branch issue_97. Please review. Some changes from branch issue_26 seems to be merged into issue_97 (or vice versa).

**Comment by tthuem** [comment]
If the issue is not in review anymore and not in progress again or closed, I'm confused what is planned now :)

Marcus, please clearify the current state.

**Comment by skrieter** [comment]
Done, merged into Master.
